# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_bnblisting_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bnbreview',
            name='host_id',
        ),
        migrations.AddField(
            model_name='bnbreview',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='bnbreview',
            table='airbnb_listing_review',
        ),
    ]
