# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0003_auto_20181024_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnblisting',
            name='review_per_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
