# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('code', models.PositiveIntegerField(default=1001, primary_key=True, serialize=False)),
                ('enable_emailing', models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1)),
                ('auto_activate_users', models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Configuration',
                'verbose_name': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='DefaultUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('code', models.PositiveIntegerField(default=1005, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Law Reform Commission', max_length=100)),
                ('productname', models.CharField(default='Logistics', max_length=255)),
                ('tele', models.CharField(max_length=18)),
                ('fax', models.CharField(blank=True, max_length=18, null=True)),
                ('www', models.URLField(max_length=255)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField()),
                ('history', models.TextField(blank=True, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('idcode', models.CharField(default='LRC', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'InstitutionInformation',
                'verbose_name': 'InstitutionInformation',
            },
        ),
    ]
