# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnblisting',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
