# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='active',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='division',
            name='active',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='active',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='head',
            name='active',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profession',
            name='active',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='unit',
            name='active',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
